// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWI-Me4ykACp5PvpbChfdmNXfl6z8ZNOM',
    appId: '1:533779434166:web:af83dd060bf65f6a967417',
    messagingSenderId: '533779434166',
    projectId: 'smartmirror-4de0f',
    authDomain: 'smartmirror-4de0f.firebaseapp.com',
    storageBucket: 'smartmirror-4de0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJBcpbhQ1PmKGX7SUuDweDkSBHjFw1Qf4',
    appId: '1:533779434166:android:6c338f9ba72bee24967417',
    messagingSenderId: '533779434166',
    projectId: 'smartmirror-4de0f',
    storageBucket: 'smartmirror-4de0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiYI2QH_p78S_AG2NRgSQZsNQ3oyYVuT8',
    appId: '1:533779434166:ios:4ae0be96fbd112f6967417',
    messagingSenderId: '533779434166',
    projectId: 'smartmirror-4de0f',
    storageBucket: 'smartmirror-4de0f.appspot.com',
    iosBundleId: 'com.example.smartmirror',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiYI2QH_p78S_AG2NRgSQZsNQ3oyYVuT8',
    appId: '1:533779434166:ios:9ab0ace48e00eb43967417',
    messagingSenderId: '533779434166',
    projectId: 'smartmirror-4de0f',
    storageBucket: 'smartmirror-4de0f.appspot.com',
    iosBundleId: 'com.example.smartmirror.RunnerTests',
  );
}
